export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE'
export const RECEIVE_USER_PROFILE_SUCCESS = 'RECEIVE_USER_PROFILE_SUCCESS'
export const RECEIVE_USER_PROFILE_FAIL = 'RECEIVE_USER_PROFILE_FAIL'

export const REQUEST_USER_REPOS = 'REQUEST_USER_REPOS'
export const RECEIVE_USER_REPOS_SUCCESS = 'RECEIVE_USER_REPOS_SUCCESS'
export const RECEIVE_USER_REPOS_FAIL = 'RECEIVE_USER_REPOS_FAIL'

